preview: false
services:
  - type: web
    name: flaclessless-backend
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: python wsgi.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
